ALTER TABLE supplier
  ADD COLUMN IF NOT EXISTS types JSONB NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN supplier.types IS '供应商类型多选：BOOKING_AGENT/FLEET/CUSTOMS_BROKER/WAREHOUSE/DEDICATED_LINE/CONTAINER_LEASING/OTHER';
